name: Build and publish release

on:
  push:
    branches:
      - ci

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      - run: nuget restore Deceive.sln
      - name: Build
        run: msbuild Deceive.sln -t:rebuild -property:Configuration=Release
      - shell: bash
        run: echo "TAG_NAME=$(date +%Y%m%d.%H%M%S)" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "**/bin/**/*.exe"
          fail_on_unmatched_files: true
          generate_release_notes: true
          tag_name: ${{ env.TAG_NAME }}
          name: Deceive ${{ env.TAG_NAME }}
